name: Test and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-run:
    runs-on: ubuntu-latest
    env: 
      PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
      PACT_BROKER_USERNAME: ${{ secrets.PACT_BROKER_USERNAME }}
      PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}
      GITHUB_REF_NAME: ${{ github.ref_name }}
      GITHUB_SHA: ${{ github.sha }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run tests
        run: pytest consumer/test_contract.py -v

      - name: Run script
        run: |
          chmod +x ./scripts/publish_contracts.sh
          ./scripts/publish_contracts.sh
          
      - name: Install Pact CLI
        run: npm install -g @pact-foundation/pact-cli
            
      - name: Can I Deploy?
        run: |
            pact-broker can-i-deploy \
            --pacticipant "UserServiceConsumer" \
            --version "$GITHUB_SHA" \
            --broker-base-url "${{ secrets.PACT_BROKER_URL }}" \
            --retry-while-unknown 10 \
            --retry-interval 10  
